import type { NextPage } from "next";
import Head from "next/head";
import Testing from "./Testing";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        hello
        <Testing />
      </main>
    </div>
  );
};

export default Home;
